begin;

create extension if not exists pg_trgm;

alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists home_area text;
alter table public.reports add column if not exists duplicate_of uuid references public.reports(id) on delete set null;
alter table public.reports add column if not exists seed_key text;
alter table public.reports add column if not exists duplicate_count integer not null default 0;
alter table public.reports drop constraint if exists reports_seed_key_unique;
alter table public.reports add constraint reports_seed_key_unique unique (seed_key);
alter table public.resources add column if not exists seed_key text;
alter table public.resources drop constraint if exists resources_seed_key_unique;
alter table public.resources add constraint resources_seed_key_unique unique (seed_key);
create index if not exists reports_title_trgm_idx on public.reports using gin (title gin_trgm_ops);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  label text not null
);

create table if not exists public.volunteer_applications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  motivation text,
  availability jsonb not null default '{}'::jsonb,
  radius_km integer not null default 10 check (radius_km between 1 and 100),
  location geography(point, 4326),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.volunteer_skills (
  user_id uuid not null references public.profiles(id) on delete cascade,
  skill_id bigint not null references public.skills(id) on delete cascade,
  primary key (user_id, skill_id)
);

create table if not exists public.report_media (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references public.reports(id) on delete cascade,
  uploaded_by uuid references public.profiles(id) on delete set null,
  kind text not null check (kind in ('original', 'admin', 'update', 'after', 'dispute')),
  storage_path text not null,
  sha256 text,
  phash text,
  lat double precision,
  lng double precision,
  accuracy_m real,
  captured_at timestamptz,
  capture_nonce text,
  ai_label jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.task_updates (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  status text,
  note text,
  media_id uuid references public.report_media(id) on delete set null,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public) values ('avatars', 'avatars', true), ('report-media', 'report-media', false)
on conflict (id) do nothing;
drop policy if exists avatars_public_read on storage.objects;
create policy avatars_public_read on storage.objects for select using (bucket_id = 'avatars');
drop policy if exists avatars_owner_write on storage.objects;
create policy avatars_owner_write on storage.objects for insert to authenticated with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);
drop policy if exists report_media_owner_write on storage.objects;
create policy report_media_owner_write on storage.objects for insert to authenticated with check (bucket_id = 'report-media' and owner_id = (select auth.uid())::text);
drop policy if exists avatars_owner_update on storage.objects;
create policy avatars_owner_update on storage.objects for update to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text)
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

alter table public.resolution_confirmations add column if not exists verdict text;
alter table public.resolution_confirmations add column if not exists comment text;
update public.resolution_confirmations set verdict = case when agrees then 'confirmed' else 'disputed' end where verdict is null;
alter table public.resolution_confirmations drop constraint if exists resolution_confirmations_verdict_check;
alter table public.resolution_confirmations add constraint resolution_confirmations_verdict_check check (verdict in ('confirmed', 'disputed'));

alter table public.skills enable row level security;
alter table public.volunteer_applications enable row level security;
alter table public.volunteer_skills enable row level security;
alter table public.report_media enable row level security;
alter table public.task_updates enable row level security;

drop policy if exists skills_read_authenticated on public.skills;
drop policy if exists applications_read_own_or_admin on public.volunteer_applications;
drop policy if exists applications_insert_own on public.volunteer_applications;
drop policy if exists applications_update_admin on public.volunteer_applications;
drop policy if exists volunteer_skills_read_authenticated on public.volunteer_skills;
drop policy if exists volunteer_skills_own on public.volunteer_skills;
drop policy if exists media_read_authenticated on public.report_media;
drop policy if exists media_insert_owner on public.report_media;
drop policy if exists task_updates_read_authenticated on public.task_updates;
drop policy if exists task_updates_insert_author on public.task_updates;

create policy skills_read_authenticated on public.skills for select to authenticated using (true);
create policy applications_read_own_or_admin on public.volunteer_applications for select to authenticated using (user_id = (select auth.uid()) or public.auth_role() = 'admin');
create policy applications_insert_own on public.volunteer_applications for insert to authenticated with check (user_id = (select auth.uid()));
create policy applications_update_admin on public.volunteer_applications for update to authenticated using (public.auth_role() = 'admin') with check (public.auth_role() = 'admin');
create policy volunteer_skills_read_authenticated on public.volunteer_skills for select to authenticated using (true);
create policy volunteer_skills_own on public.volunteer_skills for all to authenticated using (user_id = (select auth.uid()) or public.auth_role() = 'admin') with check (user_id = (select auth.uid()) or public.auth_role() = 'admin');
create policy media_read_authenticated on public.report_media for select to authenticated using (true);
create policy media_insert_owner on public.report_media for insert to authenticated with check (uploaded_by = (select auth.uid()) or public.auth_role() in ('admin', 'dispatcher'));
create policy task_updates_read_authenticated on public.task_updates for select to authenticated using (true);
create policy task_updates_insert_author on public.task_updates for insert to authenticated with check (author_id = (select auth.uid()) or public.auth_role() in ('admin', 'dispatcher'));

insert into public.skills (slug, label) values
  ('medical', 'Medical'), ('logistics', 'Logistics'), ('heavy_lifting', 'Heavy lifting'), ('tech_support', 'Technical support')
on conflict (slug) do update set label = excluded.label;

create or replace function public.advance_report_status(p_report uuid, p_status text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare current_status text;
begin
  if auth.uid() is null then raise exception 'authentication required' using errcode = '42501'; end if;
  if (select role from public.profiles where id = auth.uid()) not in ('admin', 'dispatcher') then raise exception 'dispatcher access required' using errcode = '42501'; end if;
  select status into current_status from public.reports where id = p_report for update;
  if not ((current_status = 'pending' and p_status = 'triaged') or (current_status = 'triaged' and p_status = 'assigned') or (current_status = 'assigned' and p_status = 'in_progress') or (current_status = 'in_progress' and p_status = 'resolved_pending_confirmation') or (current_status = 'resolved_pending_confirmation' and p_status = 'closed') or (current_status = 'disputed' and p_status = 'reopened') or (current_status = 'reopened' and p_status = 'assigned')) then
    raise exception 'illegal report transition: % -> %', current_status, p_status using errcode = '22023';
  end if;
  update public.reports set status = p_status, updated_at = now() where id = p_report;
end;
$$;

create or replace function public.confirm_report_resolution(p_report uuid, p_agrees boolean, p_image_path text default null)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare reporter uuid;
begin
  if auth.uid() is null then raise exception 'authentication required' using errcode = '42501'; end if;
  select reporter_id into reporter from public.reports where id = p_report and status = 'resolved_pending_confirmation';
  if reporter is null then raise exception 'report is not awaiting confirmation' using errcode = '22023'; end if;
  if p_agrees then
    insert into public.resolution_confirmations (report_id, user_id, agrees, verdict, image_path)
    values (p_report, auth.uid(), true, 'confirmed', p_image_path)
    on conflict (report_id, user_id) do update set agrees = true, verdict = 'confirmed', image_path = excluded.image_path;
    if auth.uid() = reporter or (select count(*) from public.resolution_confirmations where report_id = p_report and verdict = 'confirmed' and user_id <> reporter) >= 2 then
      update public.reports set status = 'closed', updated_at = now() where id = p_report;
    end if;
  else
    insert into public.resolution_confirmations (report_id, user_id, agrees, verdict, image_path)
    values (p_report, auth.uid(), false, 'disputed', p_image_path)
    on conflict (report_id, user_id) do update set agrees = false, verdict = 'disputed', image_path = excluded.image_path;
    update public.reports set status = 'reopened', updated_at = now() where id = p_report;
  end if;
end;
$$;

create or replace view public.report_priority as
select r.id, r.title, r.status, r.severity,
  (case r.severity when 'critical' then 3 when 'moderate' then 2 else 1 end) * 3
  + coalesce((select count(*) from public.report_votes v where v.report_id = r.id and v.value = 1), 0)
  - coalesce((select count(*) from public.report_votes v where v.report_id = r.id and v.value = -1), 0)
  + 2 * r.duplicate_count
  + extract(epoch from (now() - r.created_at)) / 43200 as score
from public.reports r;

create or replace function public.open_reports_within(p_lat double precision, p_lon double precision, p_radius_m integer default 75, p_category text default null)
returns table (id uuid, title text, description text, category text, severity text, status text, location_label text, created_at timestamptz)
language sql
security invoker
set search_path = public
as $$
  select r.id, r.title, r.description, r.category, r.severity, r.status, r.location_label, r.created_at
  from public.reports r
  where r.status not in ('closed', 'rejected', 'duplicate')
    and r.created_at > now() - interval '30 days'
    and (p_category is null or r.category::text = p_category)
    and st_dwithin(r.location, st_setsrid(st_makepoint(p_lon, p_lat), 4326)::geography, p_radius_m)
  order by r.created_at desc;
$$;

create or replace function public.find_similar_reports(p_lat double precision, p_lon double precision, p_category text, p_title text, p_phash text default null)
returns table (id uuid, title text, category text, similarity double precision)
language sql
security invoker
set search_path = public
as $$
  select r.id, r.title, r.category,
    (0.5 * greatest(0, 1 - st_distance(r.location, st_setsrid(st_makepoint(p_lon, p_lat), 4326)::geography) / 75)
      + 0.2 * case when r.category::text = p_category then 1 else 0 end
      + 0.2 * similarity(r.title, p_title))::double precision as similarity
  from public.reports r
  where r.status not in ('closed', 'rejected', 'duplicate')
    and r.created_at > now() - interval '30 days'
    and st_dwithin(r.location, st_setsrid(st_makepoint(p_lon, p_lat), 4326)::geography, 75)
  order by similarity desc
  limit 5;
$$;

grant select on public.skills, public.report_priority to authenticated;
grant select, insert, update on public.volunteer_applications, public.volunteer_skills, public.report_media, public.task_updates to authenticated;
grant execute on function public.advance_report_status, public.open_reports_within, public.find_similar_reports to authenticated;
grant execute on function public.confirm_report_resolution to authenticated;

do $$ begin
  alter publication supabase_realtime add table public.task_updates;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.report_votes;
exception when duplicate_object then null;
end $$;

commit;